[colors.bright]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xdcdfe4"
yellow = "0xe5c07b"

[colors.normal]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xdcdfe4"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xdcdfe4"

[font]
size = 14.0

[font.bold]
family = "Iosevka Term SS04"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term SS04"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term SS04"
style = "Italic"

[font.normal]
family = "Iosevka Term SS04"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BU"
key = "Back"
mode = "AppCursor"
mods = "Command"

[shell]
program = "/bin/zsh"

[window.padding]
x = 8
y = 8
